/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AddressBalance = IDL.Record({
  'unconfirmed' : IDL.Int,
  'confirmed' : IDL.Nat,
});
export const BridgeError = IDL.Variant({
  'not_configured' : IDL.Null,
  'malformed_response' : IDL.Text,
  'invalid_input' : IDL.Text,
  'backend_unavailable' : IDL.Text,
});
export const BridgeResult_3 = IDL.Variant({
  'ok' : AddressBalance,
  'err' : BridgeError,
});
export const HistoryEntry = IDL.Record({
  'height' : IDL.Int,
  'value' : IDL.Opt(IDL.Int),
  'txid' : IDL.Text,
});
export const AddressHistory = IDL.Record({ 'entries' : IDL.Vec(HistoryEntry) });
export const BridgeResult_2 = IDL.Variant({
  'ok' : AddressHistory,
  'err' : BridgeError,
});
export const BridgeOperatorStatus = IDL.Record({
  'isOperator' : IDL.Bool,
  'operatorConfigured' : IDL.Bool,
});
export const BridgeStatus = IDL.Record({
  'checkpointConfigured' : IDL.Bool,
  'configured' : IDL.Bool,
});
export const FeeEstimate = IDL.Record({ 'satoshisPerKb' : IDL.Nat });
export const BridgeResult_1 = IDL.Variant({
  'ok' : FeeEstimate,
  'err' : BridgeError,
});
export const ServerStatus = IDL.Record({
  'height' : IDL.Int,
  'protocolVersion' : IDL.Text,
  'checkpointConfigured' : IDL.Bool,
  'serverVersion' : IDL.Text,
  'checkpointHeight' : IDL.Opt(IDL.Nat),
  'checkpointHash' : IDL.Opt(IDL.Text),
});
export const BridgeResult = IDL.Variant({
  'ok' : ServerStatus,
  'err' : BridgeError,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearBridgeConfig' : IDL.Func([], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAddressBalance' : IDL.Func([IDL.Text], [BridgeResult_3], []),
  'getAddressHistory' : IDL.Func([IDL.Text], [BridgeResult_2], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBridgeOperatorStatus' : IDL.Func([], [BridgeOperatorStatus], ['query']),
  'getBridgeStatus' : IDL.Func([], [BridgeStatus], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeeEstimate' : IDL.Func([], [BridgeResult_1], []),
  'getServerStatus' : IDL.Func([], [BridgeResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setBridgeConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setBridgeOperator' : IDL.Func([IDL.Principal], [], []),
  'transformBridgeResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : HttpRequestResult,
        }),
      ],
      [HttpRequestResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AddressBalance = IDL.Record({
    'unconfirmed' : IDL.Int,
    'confirmed' : IDL.Nat,
  });
  const BridgeError = IDL.Variant({
    'not_configured' : IDL.Null,
    'malformed_response' : IDL.Text,
    'invalid_input' : IDL.Text,
    'backend_unavailable' : IDL.Text,
  });
  const BridgeResult_3 = IDL.Variant({
    'ok' : AddressBalance,
    'err' : BridgeError,
  });
  const HistoryEntry = IDL.Record({
    'height' : IDL.Int,
    'value' : IDL.Opt(IDL.Int),
    'txid' : IDL.Text,
  });
  const AddressHistory = IDL.Record({ 'entries' : IDL.Vec(HistoryEntry) });
  const BridgeResult_2 = IDL.Variant({
    'ok' : AddressHistory,
    'err' : BridgeError,
  });
  const BridgeOperatorStatus = IDL.Record({
    'isOperator' : IDL.Bool,
    'operatorConfigured' : IDL.Bool,
  });
  const BridgeStatus = IDL.Record({
    'checkpointConfigured' : IDL.Bool,
    'configured' : IDL.Bool,
  });
  const FeeEstimate = IDL.Record({ 'satoshisPerKb' : IDL.Nat });
  const BridgeResult_1 = IDL.Variant({
    'ok' : FeeEstimate,
    'err' : BridgeError,
  });
  const ServerStatus = IDL.Record({
    'height' : IDL.Int,
    'protocolVersion' : IDL.Text,
    'checkpointConfigured' : IDL.Bool,
    'serverVersion' : IDL.Text,
    'checkpointHeight' : IDL.Opt(IDL.Nat),
    'checkpointHash' : IDL.Opt(IDL.Text),
  });
  const BridgeResult = IDL.Variant({
    'ok' : ServerStatus,
    'err' : BridgeError,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearBridgeConfig' : IDL.Func([], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAddressBalance' : IDL.Func([IDL.Text], [BridgeResult_3], []),
    'getAddressHistory' : IDL.Func([IDL.Text], [BridgeResult_2], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBridgeOperatorStatus' : IDL.Func([], [BridgeOperatorStatus], ['query']),
    'getBridgeStatus' : IDL.Func([], [BridgeStatus], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeeEstimate' : IDL.Func([], [BridgeResult_1], []),
    'getServerStatus' : IDL.Func([], [BridgeResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setBridgeConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setBridgeOperator' : IDL.Func([IDL.Principal], [], []),
    'transformBridgeResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpRequestResult,
          }),
        ],
        [HttpRequestResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };