/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressBalance { 'unconfirmed' : bigint, 'confirmed' : bigint }
export interface AddressHistory { 'entries' : Array<HistoryEntry> }
export type BridgeError = { 'not_configured' : null } |
  { 'malformed_response' : string } |
  { 'invalid_input' : string } |
  { 'backend_unavailable' : string };
export type BridgeResult = { 'ok' : ServerStatus } |
  { 'err' : BridgeError };
export type BridgeResult_1 = { 'ok' : FeeEstimate } |
  { 'err' : BridgeError };
export type BridgeResult_2 = { 'ok' : AddressHistory } |
  { 'err' : BridgeError };
export type BridgeResult_3 = { 'ok' : AddressBalance } |
  { 'err' : BridgeError };
export interface BridgeOperatorStatus { 'isOperator' : boolean, 'operatorConfigured' : boolean }
export interface BridgeStatus {
  'checkpointConfigured' : boolean,
  'configured' : boolean,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FeeEstimate { 'satoshisPerKb' : bigint }
export interface HistoryEntry {
  'height' : bigint,
  'value' : [] | [bigint],
  'txid' : string,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface ServerStatus {
  'checkpointHeight' : [] | [bigint],
  'checkpointHash' : [] | [string],
  'height' : bigint,
  'protocolVersion' : string,
  'checkpointConfigured' : boolean,
  'serverVersion' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Clears the bridge configuration. Admin-only. After this, every read
   * / returns `#not_configured`.
   */
  'clearBridgeConfig' : ActorMethod<[], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Reads an address balance through the bridge.
   */
  'getAddressBalance' : ActorMethod<[string], BridgeResult_3>,
  /**
   * / Reads address history through the bridge.
   */
  'getAddressHistory' : ActorMethod<[string], BridgeResult_2>,
  /**
   * / Reports only whether a bridge is configured. Never returns the URL or
   * / secret.
   */
  'getBridgeStatus' : ActorMethod<[], BridgeStatus>,
  'getBridgeOperatorStatus' : ActorMethod<[], BridgeOperatorStatus>,
  'setBridgeOperator' : ActorMethod<[Principal], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Reads a fee estimate through the bridge. The bridge requires a target
   * / block count in `[1, 1008]`; the canister uses a fixed default.
   */
  'getFeeEstimate' : ActorMethod<[], BridgeResult_1>,
  /**
   * / Reads server/network status through the bridge. Uses the allowlisted
   * / `server.version` method (there is no `server.status` on the bridge). The
   * / checkpoint is reported as unconfigured.
   */
  'getServerStatus' : ActorMethod<[], BridgeResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Sets the bridge base URL and deployment secret. Admin-only. The URL must
   * / be HTTPS. Neither value is echoed back.
   */
  'setBridgeConfig' : ActorMethod<[string, string], undefined>,
  /**
   * / Consensus-safe transform: strips volatile headers so all replicas agree
   * / on the response. The body is passed through unchanged.
   */
  'transformBridgeResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpRequestResult }],
    HttpRequestResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];