/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressBalance { 'unconfirmed' : bigint, 'confirmed' : bigint }
export interface AddressHistory { 'entries' : Array<HistoryEntry> }
export interface AddressUtxos { 'utxos' : Array<Utxo> }
export type BridgeError = { 'not_configured' : null } |
  { 'malformed_response' : string } |
  { 'invalid_input' : string } |
  { 'backend_unavailable' : string };
export interface BridgeOperatorStatus {
  'isOperator' : boolean,
  'operatorConfigured' : boolean,
}
export type BridgeResult = { 'ok' : ServerStatus } |
  { 'err' : BridgeError };
export type BridgeResult_1 = { 'ok' : RawTransaction } |
  { 'err' : BridgeError };
export type BridgeResult_2 = { 'ok' : FeeEstimate } |
  { 'err' : BridgeError };
export type BridgeResult_3 = { 'ok' : AddressUtxos } |
  { 'err' : BridgeError };
export type BridgeResult_4 = { 'ok' : AddressHistory } |
  { 'err' : BridgeError };
export type BridgeResult_5 = { 'ok' : AddressBalance } |
  { 'err' : BridgeError };
export type BridgeResult_6 = { 'ok' : BroadcastReceipt } |
  { 'err' : BridgeError };
export interface BridgeStatus {
  'checkpointConfigured' : boolean,
  'configured' : boolean,
}
export interface BroadcastReceipt { 'txid' : string, 'outcome' : string }
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FeeEstimate { 'satoshisPerKb' : bigint }
export interface HistoryEntry {
  'height' : bigint,
  'value' : [] | [bigint],
  'txid' : string,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface RawTransaction { 'hex' : string }
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface ServerStatus {
  'height' : bigint,
  'protocolVersion' : string,
  'checkpointConfigured' : boolean,
  'serverVersion' : string,
  'checkpointHeight' : [] | [bigint],
  'broadcastEnabled' : [] | [boolean],
  'checkpointHash' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Utxo {
  'height' : bigint,
  'value' : bigint,
  'txid' : string,
  'vout' : number,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / No keys or signing: only already-signed narrow-format transaction bytes.
   * / Any outcall failure may be an unknown broadcast outcome; callers must
   * / retain/reconcile the same bytes and never automatically rebuild a payment.
   */
  'broadcastSignedTransaction' : ActorMethod<[string, string], BridgeResult_6>,
  'clearBridgeConfig' : ActorMethod<[], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getAddressBalance' : ActorMethod<[string], BridgeResult_5>,
  'getAddressHistory' : ActorMethod<[string], BridgeResult_4>,
  'getAddressUtxos' : ActorMethod<[string], BridgeResult_3>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBridgeOperatorStatus' : ActorMethod<[], BridgeOperatorStatus>,
  'getBridgeStatus' : ActorMethod<[], BridgeStatus>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeeEstimate' : ActorMethod<[], BridgeResult_2>,
  'getRawTransaction' : ActorMethod<[string], BridgeResult_1>,
  'getServerStatus' : ActorMethod<[], BridgeResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
  'setBridgeConfig' : ActorMethod<[string, string], undefined>,
  /**
   * / Recovery/rotation is controller-only. Public login roles confer no power.
   */
  'setBridgeOperator' : ActorMethod<[Principal], undefined>,
  'transformBridgeResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpRequestResult }],
    HttpRequestResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];